### ISSUE TITLE
client.Stats.Network doesn't work

### ISSUE THREAD

**Issue by thanhson1085** [fsouza/go-dockerclient#433]
I tried to use go-dockerclient to get data from Docker Stats Api. It work fine. Thank for your source code.

Only Stats.Network data always is empty `Network Stats {0 0 0 0 0 0 0 0}`

I checked stats data that returned from /containers/{id}/stats:

```
  networks: 
   { eth0: 
      { rx_bytes: 1491409627,
        rx_packets: 3274818,
        rx_errors: 0,
        rx_dropped: 0,
        tx_bytes: 1631126564,
        tx_packets: 3559559,
        tx_errors: 0,
        tx_dropped: 0 } }
```

Please take a look: https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/
I saw the different between Json Data and Network Struct. I think that it should be fixed. Thank you in advance.

**Comment by fsouza** [comment]
Hi @thanhson1085, thanks for reporting this issue. The code was broken because we've added support for NetworkStats before docker-network was out!

I've just merged #436, so I'm closing this issue now.

**Comment by beetree** [comment]
I'm still having this issue.

Starting a container with:
```
docker run -it ubuntu /bin/bash -c "apt-get -y install wget && wget --limit-rate=100k http://releases.ubuntu.com/raring/ubuntu-13.04-server-amd64.iso"
```

My code is:
```
package main

import (
	"github.com/fsouza/go-dockerclient"
	"fmt"
	"time"
	"errors"
)

const DockerAddress string = "unix:///var/run/docker.sock"
	
func DockerContainerStatsGetRead(id string) (stats *docker.Stats, err error) {
	client, err := docker.NewClient(DockerAddress)
	if err != nil { fmt.Println(err.Error()); return; }

	errChannel := make(chan error, 1)
	statsChannel := make(chan *docker.Stats)

	opts := docker.StatsOptions {
		ID: id,
		Stats: statsChannel,
		Stream: false,
		Timeout: 10*time.Second,
	}
	
	go func() {
		errChannel <- client.Stats(opts)
	}()

	stats, ok := <- statsChannel
	if !ok {
		err = errors.New("Bad response getting stats for container: " + id)
		fmt.Println(err.Error())
		return
	}

	err = <- errChannel
	if err != nil { fmt.Println(err.Error()); return; }
	
	return
}

func main() {
	dockerContainer := "00e6d8cba17a"

	stats, err := DockerContainerStatsGetRead(dockerContainer)
	if err != nil { fmt.Println(err.Error()); return; }

	fmt.Println(stats.MemoryStats.Usage)
	fmt.Println(stats.Network)

	time.Sleep(1 * time.Second)

	stats2, err := DockerContainerStatsGetRead(dockerContainer)
	if err != nil { fmt.Println(err.Error()); return; }

	fmt.Println(stats2.MemoryStats.Usage)
	fmt.Println(stats2.Network)
}
```

The output is:
```
# ./test.sh
45178880
{0 0 0 0 0 0 0 0}
45572096
{0 0 0 0 0 0 0 0}
```
(it works retrieving memory stats, but it doesn't work retrieving network stats)

Background info on docker / system:
```
# docker info
Containers: 3
 Running: 1
 Paused: 0
 Stopped: 2
Images: 1
Server Version: 1.10.2
Storage Driver: devicemapper
 Pool Name: docker-8:1-1053029-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 2.147 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 606.3 MB
 Data Space Total: 214.7 GB
 Data Space Available: 36.7 GB
 Metadata Space Used: 1.507 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.99 (2015-06-20)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.0-040400rc8-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 24
Total Memory: 7.794 GiB
Name: ubuntu
ID: O6JD:MGK4:2SWN:D2TC:SIRV:53OE:IKCM:2C37:YZDF:2XOO:HQBF:UXZY
Username: eleet
Registry: https://index.docker.io/v1/
WARNING: No swap limit support


# docker version
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:40:35 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:40:35 2016
 OS/Arch:      linux/amd64

# uname -a
Linux ubuntu 4.4.0-040400rc8-generic #201601051225 SMP Tue Jan 5 17:27:39 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

It's a fresh `go get` from github and seems to have all the latest updates, including https://github.com/thanhson1085/go-dockerclient/commit/adc42c2863dd78dcabe6b50b649a7ac1cee8b5c2:
```
# ls -la /root/go/src/github.com/fsouza/go-dockerclient/container.go
-rwxrwxrwx 1 root root 47296 Mar  5 08:48 /root/go/src/github.com/fsouza/go-dockerclient/container.go


# grep -C 5 "NetworkStats" /root/go/src/github.com/fsouza/go-dockerclient/container.go
// Stats represents container statistics, returned by /containers/<id>/stats.
//
// See https://goo.gl/GNmLHb for more details.
type Stats struct {
        Read        time.Time               `json:"read,omitempty" yaml:"read,omitempty"`
        Network     NetworkStats            `json:"network,omitempty" yaml:"network,omitempty"`
        Networks    map[string]NetworkStats `json:"networks,omitempty" yaml:"networks,omitempty"`
        MemoryStats struct {
                Stats struct {
                        TotalPgmafault          uint64 `json:"total_pgmafault,omitempty" yaml:"total_pgmafault,omitempty"`
                        Cache                   uint64 `json:"cache,omitempty" yaml:"cache,omitempty"`
                        MappedFile              uint64 `json:"mapped_file,omitempty" yaml:"mapped_file,omitempty"`
--
        } `json:"blkio_stats,omitempty" yaml:"blkio_stats,omitempty"`
        CPUStats    CPUStats `json:"cpu_stats,omitempty" yaml:"cpu_stats,omitempty"`
        PreCPUStats CPUStats `json:"precpu_stats,omitempty"`
}

// NetworkStats is a stats entry for network stats
type NetworkStats struct {
        RxDropped uint64 `json:"rx_dropped,omitempty" yaml:"rx_dropped,omitempty"`
        RxBytes   uint64 `json:"rx_bytes,omitempty" yaml:"rx_bytes,omitempty"`
        RxErrors  uint64 `json:"rx_errors,omitempty" yaml:"rx_errors,omitempty"`
        TxPackets uint64 `json:"tx_packets,omitempty" yaml:"tx_packets,omitempty"`
        TxDropped uint64 `json:"tx_dropped,omitempty" yaml:"tx_dropped,omitempty"`
```


Also `docker stats` does return network usage:
```
# docker stats --no-stream $(docker ps -q)
CONTAINER           CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O
00e6d8cba17a        0.07%               77.59 MB / 8.369 GB   0.93%               35.54 MB / 210 kB   36.95 MB / 10.18 MB
```

Would be great if you could either point me to what I'm doing wrong, or help point me to how I help fix the lib.

Thanks!

**Comment by erolg** [comment]
@beetree @fsouza still having same issue.

**Comment by fsouza** [comment]
I'm reopening for reviewing what's going on, thanks for letting me know!

@beetree sorry for taking that long to reopen the issue.

**Comment by beetree** [comment]
No problem, hoping to have it fixed soon :)
